stream:
    camera_1: http://188.187.189.247:555/OYGNXIEJ?container=mjpeg&stream=sub
    camera_2: http://188.187.189.247:555/OYGNXIEJ?container=mjpeg&stream=sub
    camera_3: http://188.187.189.247:555/OYGNXIEJ?container=mjpeg&stream=sub